# Generated by Django 4.0.1 on 2022-02-15 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_address_alter_user_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='user name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=13, validators=[django.core.validators.MaxLengthValidator(13, 'phone number is too long'), django.core.validators.MinLengthValidator(11, 'phone number length is too short')], verbose_name='phone'),
            preserve_default=False,
        ),
    ]
