# Generated by Django 4.0.1 on 2022-01-16 18:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='customer name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='customer email')),
                ('address', models.TextField(blank=True, verbose_name='customer address')),
                ('phone', models.CharField(blank=True, max_length=13, validators=[django.core.validators.MaxLengthValidator(13, 'phone number is too long'), django.core.validators.MinLengthValidator(11, 'phone number length is too short')], verbose_name='customer phone number')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='customer joined')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='customer specs updated')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='contents')),
                ('order_id', models.CharField(blank=True, max_length=10, verbose_name='order id')),
                ('authority', models.CharField(blank=True, max_length=50, verbose_name='authority code')),
                ('peigiry', models.CharField(blank=True, max_length=6, verbose_name='peigiry code')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, verbose_name='price')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('start', models.DateField(blank=True, verbose_name='project start date')),
                ('end', models.DateField(blank=True, verbose_name='project end time(est)')),
                ('is_ready', models.BooleanField(default=False, verbose_name='project ready')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='project delivered to customer')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='order created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='order updated')),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='customer')),
            ],
        ),
    ]
