# Generated by Django 4.0.1 on 2022-01-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customer_name_alter_customer_phone'),
        ('core', '0004_alter_customer_name'),
    ]

    operations = [
    ]
