# Generated by Django 4.0.1 on 2022-02-15 08:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_customer_address_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='customer address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='customer email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=13, validators=[django.core.validators.MaxLengthValidator(13, 'phone number is too long'), django.core.validators.MinLengthValidator(11, 'phone number length is too short')], verbose_name='customer phone number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, default='', verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='authority',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='authority code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='order id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='peigiry',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='peigiry code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, default='', verbose_name='slug'),
            preserve_default=False,
        ),
    ]
