# Generated by Django 4.0.1 on 2022-02-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='authority',
        ),
        migrations.RemoveField(
            model_name='order',
            name='peigiry',
        ),
        migrations.AddField(
            model_name='payment',
            name='authority',
            field=models.CharField(blank=True, max_length=50, verbose_name='authority code'),
        ),
        migrations.AddField(
            model_name='payment',
            name='peigiry',
            field=models.CharField(blank=True, max_length=6, verbose_name='peigiry code'),
        ),
    ]
