# Generated by Django 4.0.1 on 2022-02-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_payment_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='message',
            field=models.TextField(blank=True, verbose_name='customer message'),
        ),
    ]
