# Generated by Django 4.0.1 on 2022-07-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='total_service',
            field=models.PositiveIntegerField(default=0, verbose_name='total service'),
        ),
    ]
