# Generated by Django 4.0.1 on 2022-07-24 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_orderservice_total_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderservice_customer', to=settings.AUTH_USER_MODEL, verbose_name='customer'),
        ),
    ]
