# Generated by Django 4.0.1 on 2022-01-16 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='customer name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.MaxLengthValidator(13, 'phone number is too long'), django.core.validators.MinLengthValidator(11, 'phone number length is too short')], verbose_name='customer phone number'),
        ),
    ]
