# Generated by Django 4.0.1 on 2022-01-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_end_alter_order_price_alter_order_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='customer name'),
        ),
    ]
