# Generated by Django 4.0.1 on 2022-01-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20220123_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.DecimalField(decimal_places=0, default=-1, max_digits=12, verbose_name='current payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='remain',
            field=models.DecimalField(decimal_places=0, default=-1, max_digits=12, verbose_name='remain price'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='customer name'),
        ),
    ]
