# Generated by Django 4.0.1 on 2022-02-14 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_pay_order_remain_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='customer address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='customer email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='customer name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MaxLengthValidator(13, 'phone number is too long'), django.core.validators.MinLengthValidator(11, 'phone number length is too short')], verbose_name='customer phone number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='order',
            name='authority',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='authority code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='contents'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='order id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='peigiry',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='peigiry code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
    ]
