# Generated by Django 4.0.1 on 2022-02-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_order_authority_remove_order_peigiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='extra_data',
            field=models.JSONField(blank=True, null=True, verbose_name='extra data'),
        ),
    ]
