# Generated by Django 4.0.1 on 2022-02-27 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_payment_extra_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='extra_data',
        ),
    ]
