# Generated by Django 4.0.1 on 2022-06-24 10:05

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_name_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='', verbose_name='profile background'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='', verbose_name='user picture'),
        ),
    ]
