# Generated by Django 4.0.1 on 2022-07-24 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_minute_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_sub', to='blog.comment'),
        ),
    ]
