# Generated by Django 4.0.1 on 2022-07-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_content_type_alter_comment_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='ناشناس', max_length=50, verbose_name='name'),
        ),
    ]
