# Generated by Django 4.0.1 on 2022-07-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='session_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='session id'),
        ),
    ]
