# Generated by Django 4.0.1 on 2022-07-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ip_v4',
            field=models.CharField(blank=True, max_length=15, verbose_name='IP address v4'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ip_v6',
            field=models.CharField(blank=True, max_length=46, verbose_name='IP address v6'),
        ),
    ]
