# Generated by Django 4.0.1 on 2022-06-23 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
                ('describe', models.CharField(blank=True, max_length=100, verbose_name='describe')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='like')),
                ('dislike', models.PositiveIntegerField(default=0, verbose_name='dislike')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', tinymce.models.HTMLField(verbose_name='content')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='likes')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='publish date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('slug', models.SlugField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_author', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'ordering': ['-publish_date', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['author', 'title', '-publish_date'], name='blog_blog_author__c6c131_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['content'], name='content_index'),
        ),
    ]
