# Generated by Django 4.0.1 on 2022-06-25 10:03

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='', verbose_name='title image'),
        ),
    ]
